-- =============================================================================
-- 0000_schema_reference.sql  ·  Referencia del esquema (multi-tenant)
-- =============================================================================
--
-- Este archivo DOCUMENTA la estructura actual de la base de datos para que el
-- proyecto sea reproducible (desplegar en un Supabase nuevo, onboarding, etc.).
--
-- ⚠️ Tu proyecto Supabase YA tiene estas tablas creadas. NO hace falta ejecutar
--    este archivo sobre tu base de datos actual. Las políticas de seguridad
--    vigentes se corrigen en 0001_fix_rls.sql.
--
-- Úsalo como referencia o como punto de partida para un entorno limpio. Revisa
-- la definición de get_mi_negocio_id() y el trigger de alta contra tu proyecto:
-- pueden diferir en detalles que no son visibles desde el código de la app.
-- =============================================================================

-- Extensiones usadas por los defaults (uuid_generate_v4 / gen_random_uuid).
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Tablas
-- -----------------------------------------------------------------------------
create table if not exists public.negocios (
  id            uuid primary key default gen_random_uuid(),
  nombre        text not null,
  auth_user_id  uuid not null,
  slug          text unique,
  created_at    timestamptz not null default timezone('utc', now())
);

create table if not exists public.ajustes (
  id                    bigint generated by default as identity primary key,
  negocio_id            uuid references public.negocios(id) on delete cascade,
  nombre_negocio        text,
  hora_apertura         smallint default 8,
  hora_cierre           smallint default 22,
  hora_inicio_descanso  integer  default 14,
  hora_fin_descanso     integer  default 15,
  created_at            timestamptz not null default now()
);

create table if not exists public.profesionales (
  id            uuid primary key default gen_random_uuid(),
  negocio_id    uuid references public.negocios(id) on delete cascade,
  nombre        text not null,
  color         text default '#6366f1',
  fecha_borrado timestamptz,
  created_at    timestamptz default timezone('utc', now())
);

create table if not exists public.servicios (
  id            bigint generated by default as identity primary key,
  negocio_id    uuid references public.negocios(id) on delete cascade,
  nombre        text,
  precio        numeric,
  duracion      integer default 60,
  fecha_borrado timestamptz,
  created_at    timestamptz not null default now()
);

create table if not exists public.clientes (
  id            uuid primary key default gen_random_uuid(),
  negocio_id    uuid references public.negocios(id) on delete cascade,
  nombre        text not null,
  telefono      text,
  email         text,
  notas         text,
  fecha_borrado timestamptz,
  created_at    timestamptz not null default timezone('utc', now())
);

create table if not exists public.citas (
  id             uuid primary key default gen_random_uuid(),
  negocio_id     uuid references public.negocios(id) on delete cascade,
  cliente_id     uuid references public.clientes(id),
  cliente_nombre text not null,
  servicio       text not null,
  profesional_id uuid references public.profesionales(id),
  fecha_inicio   timestamptz not null,
  fecha_fin      timestamptz not null,
  precio         numeric,
  estado         text default 'pendiente',
  fecha_borrado  timestamptz,
  creado_en      timestamptz default now()
);

create table if not exists public.cierres_negocio (
  id            uuid primary key default uuid_generate_v4(),
  ajustes_id    bigint references public.ajustes(id) on delete cascade,
  fecha         date not null,
  motivo        text,
  fecha_borrado timestamptz
);

-- -----------------------------------------------------------------------------
-- Helper multi-tenant: devuelve el negocio del usuario autenticado.
-- Es la pieza sobre la que se apoyan todas las políticas RLS del panel privado.
-- -----------------------------------------------------------------------------
create or replace function public.get_mi_negocio_id()
returns uuid
language sql
security definer
stable
as $$
  select id from public.negocios where auth_user_id = auth.uid() limit 1;
$$;

-- -----------------------------------------------------------------------------
-- Activar RLS en todas las tablas.
-- -----------------------------------------------------------------------------
alter table public.negocios        enable row level security;
alter table public.ajustes         enable row level security;
alter table public.profesionales   enable row level security;
alter table public.servicios       enable row level security;
alter table public.clientes        enable row level security;
alter table public.citas           enable row level security;
alter table public.cierres_negocio enable row level security;

-- -----------------------------------------------------------------------------
-- Políticas: cada negocio solo accede a SUS datos (panel privado).
-- El portal público NO usa estas políticas: va por el backend (service_role).
-- -----------------------------------------------------------------------------
drop policy if exists "Ver propio negocio" on public.negocios;
create policy "Ver propio negocio" on public.negocios
  for select using (auth.uid() = auth_user_id);

drop policy if exists "Editar propio negocio" on public.negocios;
create policy "Editar propio negocio" on public.negocios
  for update using (auth.uid() = auth_user_id);

drop policy if exists "Acceso ajustes" on public.ajustes;
create policy "Acceso ajustes" on public.ajustes
  for all using (negocio_id = public.get_mi_negocio_id());

drop policy if exists "Acceso profesionales" on public.profesionales;
create policy "Acceso profesionales" on public.profesionales
  for all using (negocio_id = public.get_mi_negocio_id());

drop policy if exists "Acceso servicios" on public.servicios;
create policy "Acceso servicios" on public.servicios
  for all using (negocio_id = public.get_mi_negocio_id());

drop policy if exists "Acceso clientes" on public.clientes;
create policy "Acceso clientes" on public.clientes
  for all using (negocio_id = public.get_mi_negocio_id());

drop policy if exists "Acceso citas" on public.citas;
create policy "Acceso citas" on public.citas
  for all using (negocio_id = public.get_mi_negocio_id());

drop policy if exists "Acceso cierres propios" on public.cierres_negocio;
create policy "Acceso cierres propios" on public.cierres_negocio
  for all using (
    ajustes_id in (
      select a.id from public.ajustes a
      where a.negocio_id = public.get_mi_negocio_id()
    )
  )
  with check (
    ajustes_id in (
      select a.id from public.ajustes a
      where a.negocio_id = public.get_mi_negocio_id()
    )
  );

-- -----------------------------------------------------------------------------
-- NOTA sobre el alta de negocios
-- El registro (login/page.tsx) guarda nombre_negocio y slug en los metadatos
-- del usuario. La fila en `negocios` (y normalmente su `ajustes`) se crea con un
-- trigger `on auth.users` SECURITY DEFINER que NO está en el código de la app.
-- Exporta el tuyo con:  supabase db dump --schema public -f schema.sql
-- y añádelo aquí para tener el alta también versionada.
-- -----------------------------------------------------------------------------
